### ISSUE TITLE
puzzle_ext.so (LoadError)

### ISSUE THREAD

**Issue by ArtemSyzonenko** [tonytonyjan/libpuzzle_ruby#1]
I get this error after gem installing and trying to run ruby code:

```
/home/artem/.rvm/rubies/ruby-2.3.0/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /home/artem/Dropbox/re2test/test.rb
/home/artem/.rvm/gems/ruby-2.3.0/gems/libpuzzle-1.0.3/lib/libpuzzle.rb:1:in `require': libpuzzle.so.1: cannot open shared object file: No such file or directory - /home/artem/.rvm/gems/ruby-2.3.0/gems/libpuzzle-1.0.3/lib/puzzle_ext.so (LoadError)
    from /home/artem/.rvm/gems/ruby-2.3.0/gems/libpuzzle-1.0.3/lib/libpuzzle.rb:1:in `<top (required)>'
    from /home/artem/Dropbox/re2test/test.rb:1:in `require'
    from /home/artem/Dropbox/re2test/test.rb:1:in `<top (required)>'
    from -e:1:in `load'
    from -e:1:in `<main>'

Process finished with exit code 1
```

It seams file exists in correct directory

![](https://i.imgur.com/OuL60l1.png)

I test libpuzzle via command line with 

`puzzle-diff /home/artem/Dropbox/re2test/7.jpg /home/artem/Dropbox/re2test/8.jpg
`
and it worked perfectly. What I am doing wrong? Please help.

**Comment by tonytonyjan** [comment]
@Zowal, thanks for reporting, but I can't reproduce it, any other environment informations for me? A docker image would be better.

**Comment by ArtemSyzonenko** [comment]
I disappointed about libpuzzle results after some testing. This 2 files:

https://i.imgur.com/meNoGQf.jpg

https://i.imgur.com/o7ZViNt.jpg

are calculated as 0.745901 similarity. I can't rely on this tool as for my purposes it shows absolutely inadequate results. Maybe I did something wrong, but that is results of the command puzzle-diff /home/artem/Dropbox/re2test/11.jpg /home/artem/Dropbox/re2test/12.jpg

I tried https://github.com/maccman/dhash after that and it shows 0.97 similarity, whick is much better. I wanted to use libpuzzle as it can handle large sets of images, but I didn't expect such results.

**Comment by tonytonyjan** [comment]
@Zowal the default threshold of libpuzzle is 0.6, in this case, you probably want to just increase it to 0.75 or higher. Or you can preprocess your images before calculate the distance.

I've updated the gem to v1.0.4 to support threshold setting. You can take it into account after you solved this issue.

**Comment by ArtemSyzonenko** [comment]
Thank you! Maybe I need to require some other module, not 'libpuzzle'? Now I am running

```
require 'libpuzzle'

# load image
p1 = Puzzle.new('/home/artem/Dropbox/re2test/9.jpg')
p2 = Puzzle.new('/home/artem/Dropbox/re2test/10.jpg')
```

to get "cannot open shared object file: No such file or directory - /home/artem/.rvm/gems/ruby-2.3.0/gems/libpuzzle-1.0.3/lib/puzzle_ext.so (LoadError)"

**Comment by ArtemSyzonenko** [comment]
Seams something is wrong with library path http://stackoverflow.com/a/2172631/3253948

**Comment by ArtemSyzonenko** [comment]
What string should I use instead $LD_LIBRARY_PATH? 

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

**Comment by tonytonyjan** [comment]
you should find the path of libpuzzle first

**Comment by ArtemSyzonenko** [comment]
it is /home/artem/.rvm/gems/ruby-2.3.0/gems/libpuzzle-1.0.3/lib

**Comment by ArtemSyzonenko** [comment]
All I needed is to run ldconfig

**Comment by ArtemSyzonenko** [comment]
Now it's working, will play with your new settings. Thanks!

**Comment by tonytonyjan** [comment]
@Zowal good to know it finally works 👍 

I am wondering if you will open source your project? I am curious about your application.

**Comment by ArtemSyzonenko** [comment]
Oh, this is just collecting ideas stage. I wanted to create images sitemap, but after searching I realized that only xml-sitemaps.com did what I wanted — automatically creating image sitemap. So I started learning how to create such a sitemap programatically. Obviously, I need to download all images and just remove duplicates (thumbnails), so I need good image duplicates finder.

**Comment by tonytonyjan** [comment]
cool, good luck 🍀
